services:
  mongodb-primary:
    image: bitnami/mongodb:6.0
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGODB_ROOT_USER=admin
      - MONGODB_ROOT_PASSWORD=admin
      - MONGODB_REPLICA_SET_KEY=4qJT9NNt80n9idLBjLdicIK5LrXoUxVx
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=replicaset
    ports:
      - 27017:27017


  minio:
    image: bitnami/minio:2024.8.3-debian-12-r0
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: test-bucket
