services:
  mongodb:
    image: mongo:6.0
    hostname: mongodb
    restart: always
    container_name: mongodb
    ports: [27017:27017]
    volumes: [./mongodb-keyfile.key:/data/mongodb-keyfile.key]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    command:
      [
        "--replSet",
        "dbrs",
        "--keyFile",
        "/data/mongodb-keyfile.key"
      ]


  minio:
    image: bitnami/minio:2024.8.3-debian-12-r0
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: test-bucket
