{{- $baseValues := . }}
{{- range $name, $values := .Values.jobs }}

---
{{- if not ($values.sealedSecrets) }}
{{- continue }}
{{- end }}

{{- if not ($values.sealedSecrets.enabled) }}
{{- continue }}
{{- end }}

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $values.sealedSecrets.name | default ( printf "%s-sealed" $name) }}
  namespace: {{ $baseValues.Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
spec:
  encryptedData:
    {{- range $key,$value:= ($values.sealedSecrets.encryptedData | required "sealedSecrets.encryptedData is required" ) }}
    {{$key}}: {{ $value }}
    {{- end }}
{{- end }}
