package common

const (
	MONGODB__USERNAME    = "MONGODB__USERNAME"
	MONGODB__PASSWORD    = "MONGODB__PASSWORD"
	MONGODB__MECHANISM   = "MONGODB__MECHANISM"
	MONGODB__AUTH_SOURCE = "MONGODB__AUTH_SOURCE"

	MONGODB__HOSTS       = "MONGODB__HOSTS"
	MONGODB__REPLICA_SET = "MONGODB__REPLICA_SET"

	MONGODB__USE_SSL          = "MONGODB__USE_SSL"
	MONGODB__TLS_CA_CERT_PATH = "MONGODB__TLS_CA_CERT_PATH"

	MONGODB__DB_TO_BACKUP                 = "MONGODB__DB_TO_BACKUP"
	MONGODB__BACKUP_OUT_DIR               = "MONGODB__BACKUP_OUT_DIR"
	MONGODB__COLLECTION_TO_BACKUP         = "MONGODB__COLLECTIONS_TO_BACKUP"
	MONGODB__EXCLUDED_COLLECTIONS         = "MONGODB__EXCLUDED_COLLECTIONS"
	MONGODB__EXCLUDED_COLLECTION_PREFIXES = "MONGODB__EXCLUDED_COLLECTION_PREFIXES"

	S3__ENDPOINT          = "S3__ENDPOINT"
	S3__ACCESS_KEY        = "S3__ACCESS_KEY"
	S3__SECRET_ACCESS_KEY = "S3__SECRET_ACCESS_KEY"
	S3__KEEP_RESENT_N     = "S3__KEEP_RESENT_N"
	S3__BUCKET            = "S3__BUCKET"
	S3__JOB_DIR           = "S3__JOB_DIR"
)

const (
	BACKUP_DEFAULT_DIR = "/app/backup"
)
