name: Build Image & CLI

on:
  push:
    branches:
      - dev
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

concurrency: release-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: build-${{ github.ref_name }}
    outputs:
      tag: ${{ steps.build-image.outputs.tag }}
    steps:
      - id: build-image
        name: Build and Push Image
        uses: ditkrg/build-image-workflow@v1
        with:
          image: common/mongodb-backup-cli
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

  build-cli:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build for Linux (amd64)
        run: GOOS=linux GOARCH=amd64 go build -tags=nomsgpack -v -o mongodb-backup-linux-amd64 main.go

      - name: Build for Windows (amd64)
        run: GOOS=windows GOARCH=amd64 go build -tags=nomsgpack -v -o mongodb-backup-windows-amd64.exe main.go

      - name: Build for macOS (Intel)
        run: GOOS=darwin GOARCH=amd64 go build -tags=nomsgpack -v -o mongodb-backup-darwin-amd64 main.go

      - name: Build for macOS (Apple Silicon)
        run: GOOS=darwin GOARCH=arm64 go build -tags=nomsgpack -v -o mongodb-backup-darwin-arm64 main.go

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mongodb-backup-linux-amd64
            mongodb-backup-windows-amd64.exe
            mongodb-backup-darwin-amd64
            mongodb-backup-darwin-arm64

