name: Build Image

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

concurrency: release-${{ github.ref }}

jobs:
  build-cli:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: go build -tags=nomsgpack -v -o mongodb-backup main.go

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: mongodb-backup

  build-image:
    uses: ditkrg/build-image-workflow/.github/workflows/workflow.yaml@v1
    with:
      image: common/mongodb-backup-cli
    secrets:
      username: ${{ secrets.HARBOR_USER }}
      password: ${{ secrets.HARBOR_TOKEN }}
