name: Build Image & Helm Chart

on:
  push:
    branches:
      - dev
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

concurrency: release-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: build-${{ github.ref_name }}
    outputs:
      tag: ${{ steps.build-image.outputs.tag }}
    steps:
      - id: build-image
        name: Build and Push Image
        uses: ditkrg/build-image-workflow@v1
        with:
          image: common/mongodb-backup-cli
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

  build-cli:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: go build -tags=nomsgpack -v -o mongodb-backup main.go

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: mongodb-backup

      - name: Install yq
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: mikefarah/yq
          tag: v4.40.2
          cache: enable

      - name: Update Helm values
        run: |
          export VERSION=$(echo "${TAG_NAME//v}")
          yq -i '.image.tag = strenv(VERSION)' ./helm/values.yaml
          yq -i '.version = strenv(VERSION)' ./helm/Chart.yaml
          yq -i '.appVersion = strenv(VERSION)' ./helm/Chart.yaml
        env:
          TAG_NAME: ${{ github.ref_name }}

      - name: Run the Action
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "[AUTO]"
          commit_message: Automatic commit
          target_branch: update-helm-chart

      - name: Create Pr
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: update-helm-chart
          target_branch: main

      - name: install dependencies
        working-directory: ./helm
        run: helm dependency build

      - name: Push Helm chart to OCI compatible registry
        uses: bsord/helm-push@v4.2.0
        with:
          useOCIRegistry: true
          registry-url: oci://reg.dev.krd/charts
          username: ${{ secrets.HARBOR_USER }}
          access-token: ${{ secrets.HARBOR_TOKEN }}
          chart-folder: ./helm

