name: Build Image & CLI

on:
  push:
    branches:
      - dev
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

concurrency: release-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: build-${{ github.ref_name }}
    outputs:
      tag: ${{ steps.build-image.outputs.tag }}
    steps:
      - id: build-image
        name: Build and Push Image
        uses: ditkrg/build-image-workflow@v1
        with:
          image: common/mongodb-backup-cli
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_TOKEN }}

  build-cli:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: go build -tags=nomsgpack -v -o mongodb-backup main.go

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: mongodb-backup

